version: 2.1
executors:
  base:
    docker:
      - image: circleci/golang:1.12-node
    working_directory: /go/src/github.com/spatialcurrent/railgun
jobs:
  pre_deps_golang:
    executor: base
    steps:
      - checkout
      - run: git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
      - run: make deps_go
      - run: go get github.com/inconshreveable/mousetrap # for windows CLI builds
      - run: go get github.com/segmentio/chamber # for AWS docker containers
      - run: sudo chown -R circleci /go/src
      - save_cache:
          key: v1-go-src-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/src
  test:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Get shadow
          command: go get golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
      - run:
          name: Install shadow
          command: go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
      - run:
          name: Download and install errcheck
          command: go get -u github.com/kisielk/errcheck
      - run:
          name: Download and install misspell
          command: go get -u github.com/client9/misspell/cmd/misspell
      - run:
          name: Download and install ineffassign
          command: go get -u github.com/gordonklaus/ineffassign
      - run:
          name: Download and install staticheck
          command: go get -u honnef.co/go/tools/cmd/staticcheck
      - run: bash scripts/test.sh
  validate:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install Dig
          command: sudo apt update && sudo apt install dnsutils
      - run:
          name: "Update ~/.ssh/known_hosts"
          command: |
            mkdir ~/.ssh/
            touch ~/.ssh/known_hosts
            for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - run: go get github.com/spatialcurrent/go-header/...
      - run: go install github.com/spatialcurrent/go-header/cmd/goheader
      - run: goheader fix --fix-year 2019 --exit-code-on-changes 1 --verbose
  build_cli:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run: bash scripts/build_cli.sh
      - store_artifacts:
          path: bin
          destination: /
  build_javascript:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install GopherJS
          command: go get -u github.com/gopherjs/gopherjs
      - run: bash scripts/build_javascript.sh
      - store_artifacts:
          path: bin
          destination: /
  build_container:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run: GOOS=linux go build -o bin/chamber_linux_amd64 -ldflags "-linkmode external -extldflags -static" github.com/segmentio/chamber
      - run:
          name: Build Executable
          command: LDFLAGS="-X main.gitBranch=$(git branch | grep \* | cut -d ' ' -f2) -X main.gitCommit=$(git rev-list -1 HEAD)" go build -a -installsuffix cgo -o bin/railgun_linux_amd64 -ldflags "$LDFLAGS" github.com/spatialcurrent/railgun/cmd/railgun
          environment:
            CGO_ENABLED: 0
            GOOS: linux
      - run: docker build -t railgun:git-${CIRCLE_SHA1} .
      - run: sudo apt-get install python-dev python-pip
      - run: pip install awscli --upgrade --user
      - run: bash -c "$(python -m awscli ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})"
      - run: docker tag railgun:git-${CIRCLE_SHA1} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/railgun:git-${CIRCLE_SHA1}
      - run: docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/railgun:git-${CIRCLE_SHA1}
workflows:
  main:
    jobs:
      - pre_deps_golang
      - test:
          requires:
            - pre_deps_golang
      - validate:
          requires:
            - pre_deps_golang
      - build_cli:
          requires:
            - pre_deps_golang
      - build_javascript:
          requires:
            - pre_deps_golang
      - build_container:
          requires:
            - build_cli
